[package]
name = "dht22"
version = "0.0.1"

[features]
default = ["mcu_lpc17xx"]
mcu_lpc17xx = ["zinc/mcu_lpc17xx"]

[dependencies]
zinc = { path =  "../.." }
macro_platformtree = { path = "../../macro_platformtree" }
