[package]

name = "volatile_cell"
version = "1.0.0"
authors = ["Vladimir Pouzanov <farcaller@gmail.com>"]

[lib]
name = "volatile_cell"
path = "lib.rs"
test = false
doctest = false
doc = true
crate-type = ["rlib"]

[features]
replayer = ["expectest"]

[dependencies.expectest]
optional = true
