[package]
name = "blink_stm32f7"
version = "0.0.1"

[features]
default = ["mcu_stm32f7"]
mcu_stm32f7 = ["zinc/mcu_stm32f7"]

[dependencies]
zinc = { path =  "../.." }
macro_zinc = { path = "../../macro_zinc" }
