[package]
name = "blink_stm32f4"
version = "0.0.1"

[features]
default = ["mcu_stm32f4"]
mcu_stm32f4 = ["zinc/mcu_stm32f4"]

[dependencies]
zinc = { path =  "../.." }
macro_zinc = { path = "../../macro_zinc" }
