[package]
name = "lcd_tiva_c"
version = "0.0.1"

[features]
default = ["mcu_tiva_c"]
mcu_tiva_c = ["zinc/mcu_tiva_c"]

[dependencies]
zinc = { path =  "../.." }
macro_platformtree = { path = "../../macro_platformtree" }
