[package]
name = "platformtree"
version = "0.1.0"
authors = ["Zinc Developers <zinc@github.com>"]

[lib]
name = "platformtree"
plugin = true

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"
